name: pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - goos: darwin
            goarch: amd64
            executable: cardinal
          - goos: darwin
            goarch: arm64
            executable: cardinal
          - goos: linux
            goarch: amd64
            executable: cardinal
          - goos: windows
            goarch: amd64
            executable: cardinal.exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: test
        run: |
          go test -v -race ./...
      - name: Build for ${{ matrix.target.goos }}-${{ matrix.target.goarch }}
        env:
          GOOS: ${{ matrix.target.goos }}
          GOARCH: ${{ matrix.target.goarch }}
        run: |
          go build -v
      - name: Upload build artifact for ${{ matrix.target.goos }}-${{ matrix.target.goarch }}
        uses: actions/upload-artifact@v3
        with:
          name: cardinal-${{ matrix.target.goos }}-${{ matrix.target.goarch }}
          path: ${{ matrix.target.executable }}
